name: oneforall
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  intl: ^0.19.0
  carousel_slider: ^4.2.1
  firebase_core: ^2.15.0
  path_provider: ^2.1.1
  introduction_screen: ^3.1.11
  shared_preferences: ^2.2.0
  firebase_auth: ^4.7.1
  email_validator: ^2.1.17
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.5
  image_picker: ^1.0.1
  # flutter_downloader: ^1.10.5
  url_launcher: ^6.1.12
  animations: ^2.0.7
  firebase_messaging: ^14.6.5
  http: ^1.1.0
  dart_jsonwebtoken: ^2.8.2
  google_sign_in: ^6.1.4
  googleapis_auth: ^1.4.1
  async: ^2.11.0
  google_mobile_ads: ^5.0.0
  just_audio: ^0.9.35
  photo_view: ^0.14.0
  flutter_shakemywidget: ^1.0.5+1
  flame: ^1.9.1
  flame_forge2d: ^0.18.0
  google_fonts: ^6.1.0
  local_hero: ^0.3.0
  shimmer: ^3.0.0
  archive: ^3.4.9
  file_picker: ^8.0.0+1
  cloud_functions: ^4.5.8
  showcaseview: ^2.0.3
  image: ^4.1.7
  pdfx: ^2.6.0
  logger: ^2.2.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  dependency_validator: ^3.2.3
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.1

# * Launcher Icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoquality.png"
  remove_alpha_ios: true
  adaptive_icon_background: "assets/images/background_image.png"
  

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/purpwallpaper 2.png
    - assets/images/logbg.png
    - assets/audio/quizAudio.mp3
    - assets/audio/successSound.mp3
    - assets/images/logo.png
    - assets/images/builtwithflutter.png
    - assets/audio/boopSound.mp3
    - assets/images/logoanim.gif
    - assets/images/logoquality.png
    - assets/images/background_image.png
  fonts:
    - family: MyFlutterApp
      fonts: 
        - asset: icons/MyFlutterApp.ttf